In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [16]:
df = pd.read_excel('Data Set.xlsx')
df

,Study_id,Cell_id,Brand within 3s,Sound Off,Format,Platform,Question Type,Test Positive %,Control Positive %
0,1,Ads_only,1,1,Video,FB+IG,ad_recall,0.153576,0.087302
1,2,Influencer,1,1,Video,FB+IG,ad_recall,0.125000,0.029821
2,2,Ads_only,1,1,Video,FB+IG,ad_recall,0.170000,0.025440
3,3,Influencer,0,0,Mix,FB+IG,ad_recall,0.135397,0.101145
4,3,Ads_only,0,0,Mix,FB+IG,ad_recall,0.183908,0.100386
...,...,...,...,...,...,...,...,...,...
82,13,Ads_only,1,1,Image,FB+IG,purchase_intent,0.045311,0.041227
83,14,Influencer,1,1,Image,FB,purchase_intent,0.381679,0.384615
84,14,Ads_only,1,1,Image,FB,purchase_intent,0.210188,0.319588
85,15,Influencer,1,1,Image,FB+IG,purchase_intent,0.172621,0.199707
86,15,Ads_only,1,1,Image,FB+IG,purchase_intent,0.202450,0.236284

In [18]:
group_by=df.groupby('Cell_id')
group_by

In [25]:
df.pivot_table(index='Cell_id', columns='Test_Positive_%')

KeyError: 'Test_Positive_%'